name: BCCP
favicon: null
layout_spectrum: 0.12950809602625668
typography_spectrum: 0.94815558870323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.19156878045760095
  lightness: 0.06669675023294985
  saturation: 0.5846014940179884
  rhythmicContrast: 0.2612642718013376
purpose: []
